# Generated by Django 3.2 on 2021-05-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaperApp', '0002_auto_20210518_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Категория', max_length=512),
        ),
    ]
