# Generated by Django 3.2 on 2021-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaperApp', '0002_auto_20210706_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(default='Категория', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.CharField(default='Категория', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='position_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='position_ru',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
